const appConfig = {
  appName: "Discreet-Luck",
  description: "Generated by Create Next App",
  theme: {
    primaryColor: "#1976d2",
    secondaryColor: "#dc004e",
  },
};

export default appConfig;
